# Generated by Django 3.2.6 on 2021-08-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GistFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('type', models.TextField()),
                ('language', models.TextField()),
                ('raw_url', models.TextField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
                ('gists_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('forks_url', models.TextField()),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gists.gistfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gists.owner')),
            ],
        ),
    ]
